<a href="https://colab.research.google.com/github/samarthlawania/Machine-Learning/blob/main/numpy_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b = np.array([[4,5,6],[7,8,9]])
b

array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(a+b)

[[ 5  7  9]
 [11 13 15]]


In [ ]:
print(a-b)

[[-3 -3 -3]
 [-3 -3 -3]]


In [ ]:
print(a**2)

[[ 1  4  9]
 [16 25 36]]


In [ ]:
print(b**2)

[[16 25 36]
 [49 64 81]]


In [ ]:
print(a==2)

[[False  True False]
 [False False False]]


In [ ]:
np.sqrt(b)

array([[2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [ ]:
np.tan(a)

array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619]])

In [ ]:
arr = np.array([[1,2],[3,4],[5,6]])

In [ ]:
arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr.flatten()


array([1, 2, 3, 4, 5, 6])